export const Roles = {
  ADMIN_USER_CREATE: "ADMIN.USER_CREATE",
  ADMIN_USER_UPDATE: "ADMIN.USER_UPDATE",
  USER_SHAREDFILE_REVOKE: "USER.SHAREDFILE_REVOKE",
  USER_FILE_UPLOAD: "USER.FILE_UPLOAD",
  USER_FILE_DELETE: "USER.FILE_DELETE",
  ADMIN_USER_DELETE: "ADMIN.USER_DELETE",
  USER_SHAREDFILE_CREATE: "USER.SHAREDFILE_CREATE",
  USER_FILE_DOWNLOAD: "USER.FILE_DOWNLOAD",
};